# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/notify_server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/notify_server.proto\"|\n\x16RegisterSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x05\x12\x11\n\tusernames\x18\x02 \x03(\t\x12\r\n\x05uuids\x18\x03 \x03(\t\x12\x0e\n\x06secret\x18\x04 \x03(\x08\x12\r\n\x05hosts\x18\x05 \x03(\t\x12\r\n\x05ports\x18\x06 \x03(\x05\"\x19\n\x17RegisterSessionResponse2V\n\x0cNotifyServer\x12\x46\n\x0fRegisterSession\x12\x17.RegisterSessionRequest\x1a\x18.RegisterSessionResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.notify_server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERSESSIONREQUEST._serialized_start=29
  _REGISTERSESSIONREQUEST._serialized_end=153
  _REGISTERSESSIONRESPONSE._serialized_start=155
  _REGISTERSESSIONRESPONSE._serialized_end=180
  _NOTIFYSERVER._serialized_start=182
  _NOTIFYSERVER._serialized_end=268
# @@protoc_insertion_point(module_scope)
