// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

#ifndef PROTOBUF_INCLUDED_base_2eproto
#define PROTOBUF_INCLUDED_base_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_base_2eproto 

namespace protobuf_base_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_base_2eproto
namespace protobuf_serialization {
class Object;
class ObjectDefaultTypeInternal;
extern ObjectDefaultTypeInternal _Object_default_instance_;
class Object_MapStringIntEntry_DoNotUse;
class Object_MapStringIntEntry_DoNotUseDefaultTypeInternal;
extern Object_MapStringIntEntry_DoNotUseDefaultTypeInternal _Object_MapStringIntEntry_DoNotUse_default_instance_;
}  // namespace protobuf_serialization
namespace google {
namespace protobuf {
template<> ::protobuf_serialization::Object* Arena::CreateMaybeMessage<::protobuf_serialization::Object>(Arena*);
template<> ::protobuf_serialization::Object_MapStringIntEntry_DoNotUse* Arena::CreateMaybeMessage<::protobuf_serialization::Object_MapStringIntEntry_DoNotUse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace protobuf_serialization {

// ===================================================================

class Object_MapStringIntEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<Object_MapStringIntEntry_DoNotUse, 
    ::std::string, ::google::protobuf::uint64,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_UINT64,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<Object_MapStringIntEntry_DoNotUse, 
    ::std::string, ::google::protobuf::uint64,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_UINT64,
    0 > SuperType;
  Object_MapStringIntEntry_DoNotUse();
  Object_MapStringIntEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const Object_MapStringIntEntry_DoNotUse& other);
  static const Object_MapStringIntEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Object_MapStringIntEntry_DoNotUse*>(&_Object_MapStringIntEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class Object : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protobuf_serialization.Object) */ {
 public:
  Object();
  virtual ~Object();

  Object(const Object& from);

  inline Object& operator=(const Object& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Object(Object&& from) noexcept
    : Object() {
    *this = ::std::move(from);
  }

  inline Object& operator=(Object&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Object& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Object* internal_default_instance() {
    return reinterpret_cast<const Object*>(
               &_Object_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Object* other);
  friend void swap(Object& a, Object& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Object* New() const final {
    return CreateMaybeMessage<Object>(NULL);
  }

  Object* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Object>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Object& from);
  void MergeFrom(const Object& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Object* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // repeated uint64 int_array = 5;
  int int_array_size() const;
  void clear_int_array();
  static const int kIntArrayFieldNumber = 5;
  ::google::protobuf::uint64 int_array(int index) const;
  void set_int_array(int index, ::google::protobuf::uint64 value);
  void add_int_array(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      int_array() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_int_array();

  // map<string, uint64> map_string_int = 6;
  int map_string_int_size() const;
  void clear_map_string_int();
  static const int kMapStringIntFieldNumber = 6;
  const ::google::protobuf::Map< ::std::string, ::google::protobuf::uint64 >&
      map_string_int() const;
  ::google::protobuf::Map< ::std::string, ::google::protobuf::uint64 >*
      mutable_map_string_int();

  // string str = 4;
  void clear_str();
  static const int kStrFieldNumber = 4;
  const ::std::string& str() const;
  void set_str(const ::std::string& value);
  #if LANG_CXX11
  void set_str(::std::string&& value);
  #endif
  void set_str(const char* value);
  void set_str(const char* value, size_t size);
  ::std::string* mutable_str();
  ::std::string* release_str();
  void set_allocated_str(::std::string* str);

  // double floating_point = 2;
  void clear_floating_point();
  static const int kFloatingPointFieldNumber = 2;
  double floating_point() const;
  void set_floating_point(double value);

  // uint64 integer = 3;
  void clear_integer();
  static const int kIntegerFieldNumber = 3;
  ::google::protobuf::uint64 integer() const;
  void set_integer(::google::protobuf::uint64 value);

  // bool boolean = 1;
  void clear_boolean();
  static const int kBooleanFieldNumber = 1;
  bool boolean() const;
  void set_boolean(bool value);

  // @@protoc_insertion_point(class_scope:protobuf_serialization.Object)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > int_array_;
  mutable int _int_array_cached_byte_size_;
  ::google::protobuf::internal::MapField<
      Object_MapStringIntEntry_DoNotUse,
      ::std::string, ::google::protobuf::uint64,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT64,
      0 > map_string_int_;
  ::google::protobuf::internal::ArenaStringPtr str_;
  double floating_point_;
  ::google::protobuf::uint64 integer_;
  bool boolean_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_base_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Object

// bool boolean = 1;
inline void Object::clear_boolean() {
  boolean_ = false;
}
inline bool Object::boolean() const {
  // @@protoc_insertion_point(field_get:protobuf_serialization.Object.boolean)
  return boolean_;
}
inline void Object::set_boolean(bool value) {
  
  boolean_ = value;
  // @@protoc_insertion_point(field_set:protobuf_serialization.Object.boolean)
}

// double floating_point = 2;
inline void Object::clear_floating_point() {
  floating_point_ = 0;
}
inline double Object::floating_point() const {
  // @@protoc_insertion_point(field_get:protobuf_serialization.Object.floating_point)
  return floating_point_;
}
inline void Object::set_floating_point(double value) {
  
  floating_point_ = value;
  // @@protoc_insertion_point(field_set:protobuf_serialization.Object.floating_point)
}

// uint64 integer = 3;
inline void Object::clear_integer() {
  integer_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Object::integer() const {
  // @@protoc_insertion_point(field_get:protobuf_serialization.Object.integer)
  return integer_;
}
inline void Object::set_integer(::google::protobuf::uint64 value) {
  
  integer_ = value;
  // @@protoc_insertion_point(field_set:protobuf_serialization.Object.integer)
}

// string str = 4;
inline void Object::clear_str() {
  str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Object::str() const {
  // @@protoc_insertion_point(field_get:protobuf_serialization.Object.str)
  return str_.GetNoArena();
}
inline void Object::set_str(const ::std::string& value) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protobuf_serialization.Object.str)
}
#if LANG_CXX11
inline void Object::set_str(::std::string&& value) {
  
  str_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:protobuf_serialization.Object.str)
}
#endif
inline void Object::set_str(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protobuf_serialization.Object.str)
}
inline void Object::set_str(const char* value, size_t size) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protobuf_serialization.Object.str)
}
inline ::std::string* Object::mutable_str() {
  
  // @@protoc_insertion_point(field_mutable:protobuf_serialization.Object.str)
  return str_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Object::release_str() {
  // @@protoc_insertion_point(field_release:protobuf_serialization.Object.str)
  
  return str_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Object::set_allocated_str(::std::string* str) {
  if (str != NULL) {
    
  } else {
    
  }
  str_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), str);
  // @@protoc_insertion_point(field_set_allocated:protobuf_serialization.Object.str)
}

// repeated uint64 int_array = 5;
inline int Object::int_array_size() const {
  return int_array_.size();
}
inline void Object::clear_int_array() {
  int_array_.Clear();
}
inline ::google::protobuf::uint64 Object::int_array(int index) const {
  // @@protoc_insertion_point(field_get:protobuf_serialization.Object.int_array)
  return int_array_.Get(index);
}
inline void Object::set_int_array(int index, ::google::protobuf::uint64 value) {
  int_array_.Set(index, value);
  // @@protoc_insertion_point(field_set:protobuf_serialization.Object.int_array)
}
inline void Object::add_int_array(::google::protobuf::uint64 value) {
  int_array_.Add(value);
  // @@protoc_insertion_point(field_add:protobuf_serialization.Object.int_array)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
Object::int_array() const {
  // @@protoc_insertion_point(field_list:protobuf_serialization.Object.int_array)
  return int_array_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
Object::mutable_int_array() {
  // @@protoc_insertion_point(field_mutable_list:protobuf_serialization.Object.int_array)
  return &int_array_;
}

// map<string, uint64> map_string_int = 6;
inline int Object::map_string_int_size() const {
  return map_string_int_.size();
}
inline void Object::clear_map_string_int() {
  map_string_int_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::google::protobuf::uint64 >&
Object::map_string_int() const {
  // @@protoc_insertion_point(field_map:protobuf_serialization.Object.map_string_int)
  return map_string_int_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::google::protobuf::uint64 >*
Object::mutable_map_string_int() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_serialization.Object.map_string_int)
  return map_string_int_.MutableMap();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf_serialization

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_base_2eproto
